(source gnu)
(source melpa)

(depends-on "cider")
(depends-on "cask")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-indent-textobject")
(depends-on "key-chord")
(depends-on "better-defaults")
