(source gnu)
(source melpa)

(depends-on "cider")
(depends-on "cask")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-indent-textobject")
(depends-on "evil-leader")
(depends-on "key-chord")
(depends-on "better-defaults")
(depends-on "smart-mode-line")
(depends-on "goto-chg")
(depends-on "relative-line-numbers")
(depends-on "ido-vertical-mode")
